spring:
  servlet:
    multipart:
      location: ${SPRING_SERVLET_MULTIPART_LOCATION:D:/myResource/valin/uploadPath/tmp}

# 日志配置
logging:
  file:
    # 日志文件输出地址
    path: ${LOGGING_FILE_PATH:D:/myResource/valin/uploadPath/wechat_logs}